version: "3.3"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  queue:
    image: rabbitmq:3-management
    environment:
        RABBITMQ_ERLANG_COOKIE: "secret cookie"
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
        RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error}]"
    ports:
        - "5672:5672"
        - "15672:15672"
  backend:
    depends_on:
      - db
      - queue
    build:
      context: ./fastapi-ariadne
      dockerfile: backend.dockerfile
    command: bash -c "alembic -n db upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"                                              
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - ./.env
    image: backend_base
  test:
    depends_on:
      - db
      - queue
    working_dir: /app
    image: backend_base
    command: pytest
    links:
      - db
    env_file:
      - ./.env

