version: "3.3"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  queue:
    image: rabbitmq:3-management
    environment:
        RABBITMQ_ERLANG_COOKIE: "secret cookie"
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
        RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error}]"
    ports:
        - "15672:15672"
        - "5672:5672"
  backend:
    depends_on:
      - db
      - queue
    build:
      context: ./fastapi-ariadne
      dockerfile: backend.dockerfile
    ports:
      - "8000:8000"
    image: backend_base

